### ISSUE TITLE
Bug: [1.20.1] Blockstate issues with preview features

### ISSUE THREAD

**Issue by Krupicova12Kase** [zSemper/ArrayLists-MCreator-Plugin#19]
### Issue description

when I try to build I get this error (logs). This could happen with more things than just blockstates as they use the same thing and blockstates are just on top so they fail first

### How to reproduce this issue?

Update to latest plugin version and try to build with forge 1.20.1

### Minecraft Version

Other (specify in additional context)

### MCreator Version

MCreator 2025.3

### Logs

```
Executing Gradle task: build 
Build info: MCreator 2025.3.45720, forge-1.20.1, 64-bit, 16108 MB, Windows 11, JVM 21.0.8, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2026-03-16-15:49:48 
 
 
BUILD FAILED 
Task completed in 28 seconds 
 
Calculating task graph as configuration cache cannot be reused because environment variable 'MCREATOR_JVM_OPTIONS' has changed. 
> Task :processTestResources NO-SOURCE 
> Task :jarJar UP-TO-DATE 
> Task :createMinecraftArtifacts UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :compileJava FAILED 
[C:\Users\luki1\MCreatorWorkspaces\visual_recipe_editor\src\main\java\net\mcreator\visualrecipeeditor\network\NbtArrayLists.java:77](file:///C:/Users/luki1/MCreatorWorkspaces/visual_recipe_editor/src/main/java/net/mcreator/visualrecipeeditor/network/NbtArrayLists.java:77): error: patterns in switch statements are a preview feature and are disabled by default. 
                case BlockState blockState -> entry.put("Value", NbtUtils.writeBlockState(blockState)); 
                     ^ 
  (use --enable-preview to enable patterns in switch statements) 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler output below. 
[C:\Users\luki1\MCreatorWorkspaces\visual_recipe_editor\src\main\java\net\mcreator\visualrecipeeditor\network\NbtArrayLists.java:77](file:///C:/Users/luki1/MCreatorWorkspaces/visual_recipe_editor/src/main/java/net/mcreator/visualrecipeeditor/network/NbtArrayLists.java:77): error: patterns in switch statements are a preview feature and are disabled by default. 
                  case BlockState blockState -> entry.put("Value", NbtUtils.writeBlockState(blockState)); 
                       ^ 
    (use --enable-preview to enable patterns in switch statements) 
  1 error 
* Try: 
> Check your code and dependencies to fix the compilation error(s) 
> Run with --scan to generate a Build Scan (powered by Develocity). 
BUILD FAILED in 1s 
4 actionable tasks: 1 executed, 3 up-to-date 
Configuration cache entry stored. 
 
BUILD FAILED 
Task completed in 2 seconds
```

### Additional Context

Forge 1.20.1
