### ISSUE TITLE
Bug: Workspace fails to compile on 2025.3, Neoforge 1.21.8

### ISSUE THREAD

**Issue by 8BitBunnie** [zSemper/ArrayLists-MCreator-Plugin#9]
### Issue description

Creating an array list instantaneously causes my workspace to fail to compile. All relevant information is included in the screenshot.
<img width="1376" height="592" alt="Image" src="https://github.com/user-attachments/assets/15941965-a3f5-46f4-ac08-8ad995e923e4" />

### How to reproduce this issue?

Step 1: Create an array list.
Step 2: Attempt to compile.

### Minecraft Version

1.21.8 NeoForge

### MCreator Version

MCreator 2025.3

### Logs

Executing Gradle task: runClient
Build info: MCreator 2025.3.44519, neoforge-1.21.8, 64-bit, 16218 MB, Windows 11, JVM 21.0.8, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2025-11-06-20:23:04

Reusing configuration cache.
> Task :writeClientLegacyClasspath UP-TO-DATE
> Task :downloadAssets UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :createMinecraftArtifacts UP-TO-DATE
> Task :prepareClientRun UP-TO-DATE
> Task :compileJava FAILED
C:\Users\(user)\MCreatorWorkspaces\demergi\src\main\java\net\mcreator\demergi\network\DemergiModVariables.java:184: error: method getList in class CompoundTag cannot be applied to given types; ListTag aixAnimations_list = nbt.getList("aixAnimations", Tag.TAG_STRING);
 ^
 required: String
 found: String,byte
 reason: actual and formal argument lists differ in length
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler output below.
C:\Users\(user)\MCreatorWorkspaces\demergi\src\main\java\net\mcreator\demergi\network\DemergiModVariables.java:184: error: method getList in class CompoundTag cannot be applied to given types; ListTag aixAnimations_list = nbt.getList("aixAnimations", Tag.TAG_STRING);
 ^
 required: String
 found: String,byte
 reason: actual and formal argument lists differ in length
 1 error
* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.
BUILD FAILED in 2s
6 actionable tasks: 1 executed, 5 up-to-date
Configuration cache entry reused.

BUILD FAILED
Task completed in 5 seconds

**Comment by florent1-2** [comment]
l'erreur vien du generateur qui ne se trompe l'erreur est directement dans Mcreator pas dans le plugins et j'ai le meme probléme : [C:\Users\ecole\Desktop\Mode\src\main\java\net\mcreator\test\network\TestModVariables.java:288](file:///C:/Users/ecole/Desktop/Mode/src/main/java/net/mcreator/test/network/TestModVariables.java:288): error: method getList in class CompoundTag cannot be applied to given types; 
                ListTag UUID_Player_list = nbt.getList("UUID_Player", Tag.TAG_STRING); 
                                              ^ 
  required: String 
  found:    String,byte 
  reason: actual and formal argument lists differ in length 
1 error 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler output below. 
[C:\Users\ecole\Desktop\Mode\src\main\java\net\mcreator\test\network\TestModVariables.java:288](file:///C:/Users/ecole/Desktop/Mode/src/main/java/net/mcreator/test/network/TestModVariables.java:288): error: method getList in class CompoundTag cannot be applied to given types; 
                  ListTag UUID_Player_list = nbt.getList("UUID_Player", Tag.TAG_STRING); 
                                                ^ 
    required: String 
    found:    String,byte 
    reason: actual and formal argument lists differ in length 
  1 error 
* Try: 
> Check your code and dependencies to fix the compilation error(s) 
> Run with --scan to get full insights. 
BUILD FAILED in 8s
